# Tab chính
new_tab Dev

cd ~/Downloads/Nro/chronos_sever

# Pane 1 (trên cùng)
launch --title Gateway bash -c "cargo run -p gateway; exec bash"

# Split ngang (chia dưới)
launch --location=hsplit --title Login bash -c "cargo run -p login-service; exec bash"

# Split dọc bên phải
launch --location=vsplit --title Game bash -c "cargo run -p game_server; exec bash"